paths:
  model_checkpoint: "/root/autodl-fs/@ICSE_RQ3_AdaRode/Model/PIK/XLnet/Best.pth"
  augmented_data_save_path: "/root/autodl-fs/@ICSE_RQ3_AdaRode/augdata/adv_data_PIK.pickle"
  attack_result_save_path: "/root/autodl-fs/@ICSE_RQ3_AdaRode/augdata/"

parameters:
  dataname: PIK
  device: "cuda:0"
  max_iterations: 100
  accept_rate: 0.95
  patience: 20

n_workers: 2
